spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://127.0.0.1:33306/universal_manage?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static
  thymeleaf:
    cache: false # 关闭模版缓存
#    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8081
  servlet:
    context-path: /

logging:
  level:
    club.maddm: debug #这个包为debug级别

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
